name: co2-routing
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - geopandas
  - pyogrio
  - shapely>=2
  - rasterio
  - numpy
  - scipy
  - pyarrow
  - scikit-image
  - pyyaml
  - pillow
